language: go
sudo: false
notifications:
  email: false
before_install:
- go get github.com/mitchellh/gox && go install github.com/mitchellh/gox
script:
- sh build.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kQo3FLTjczS5StZlbL3aI+LnD5BBOp8ZZUglSUe8Xc3OMqi3GJwssR9cyfb/NscSzTMO+7sKq0EG4r3sNCVulLHsZw7uJcitJPCJE07z0rQdkWptmERZB0yBH18ZzofV1RXniwyjcFG/oUmBz039zjGlI9/TK91VIcHkvaIu4IxUelBRgyv4vUsHUIi10M15WtgXoJax7kwESfKMsFbDj79GrfYx+4vUSQl3fLU0SFmEKBabI9GRXFzCqe1lGgTzXZtN/Jpi87ngLym12RoJbxACHaIRLuZ6sjkLHCrDaE4jrkIfmbN74Zm+hCb5n0MeXai+mtNreWRn2UiZWjOsFWNRb9kr3uHo0B6BwVyVWB/ZkA5f5oFyxFd6O8DDb38ywqgBb9y/1hRa0KOUMokaLDyAN3G02UHr10np1VxrZ4vktiO80fpmCih5sDcoa6sWN4LxcYqD851e29PQWObcYithTzH0R6PpHyat8Mmr6TgwLN+zkYKwHijEMudINuikQpFxRIRyfdXiNzS9wXWzpTzQyr97xERf9S96N1RgHU7oNnkY4Z7zRil6i5UtjAaL+DpmLR9liRaSgOgSOe/Yg7ekEbqBGEeXD7BH19u+3egi2A81tfZQzlLMzOW70GKEkOFjNKgrt4B/ASEuefBT5K4nxAe3AWdQ+5edi/u0/oU=
  file:
    - releases/event-framework-subscriber_darwin_amd64
    - releases/event-framework-subscriber_linux_386
    - releases/event-framework-subscriber_linux_amd64
    - releases/event-framework-subscriber_linux_arm
    - releases/event-framework-subscriber_linux_arm64
    - releases/event-framework-subscriber_windows_386.exe
    - releases/event-framework-subscriber_windows_amd64.exe
  on:
    repo: KWRI/event-framework-subscriber
    tags: true
    all_branches: true

