language: go
go:
- '1.11'
branches:
  only:
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- go get github.com/mitchellh/gox && go install github.com/mitchellh/gox
before_script:
- go get ./...
script:
- sh build.sh
deploy:
  provider: releases
  api_key:
    secure: v/q/pI13JmChJLqvZHLJ6pGLBaeL/EDS42jfGJ2W1IP5QuXKczEMEIBNniR+Pj2/4aOrx/etugDIs/2agtsqfBSWHv5jgPCufpgnyNmrmx8wWDPwiXx4ZiY4YsLiXNUeRadSCwe2q4GjE9OkAM+W6kvF/y6obOUONEhCq+M/dIfH3ha76ZZdYaBAyFyATTn2BlZ68OzeIAGFQJbdHUh5ruOlI9/WQXF03j6lu6EojsbuPva4jDc3+Gclp7tiYOoQ1eght3RglYbD9amZzOu3kzufTkKFH/9ojodW0cTwh3X29TH5+J5MN51AaOQmpxHpAppKcOp99HoR6vOy2d6MVJC4JVVSIqXM8OUDR6cKxPiNTz3lXNsAeBrLllh7uaPRLMwUNG/8EkqWbVEEyb9vlk+dnsB2/xBNrBMsrLWvZx5xbisCPUJX2My5Dnz/hDo7Qjqt6fE68ewsN4U6zjA1C0kgAVsQqKAQRTBhHvE4nBxRGH+bzVjBIHVcwLe20VYPkyQ1H4RTlNlXQ71HJg0g22Nn9xZJARG/WrwN32/Wo/40+FG7XUR4vv+JJvdbXS9C5OAo3gPOmvHZRzv/1ZMM0bU/8W0unHTUbPASiKzZvjrySTVzbH9zLlcEo6+UXYlF/4de7n3j41AWixWOdUV+msa1q76zRA1SpCplqyqlSOw=
  file: releases/*
  on:
    tags: true
